### ISSUE TITLE
Add documentation for `esp-hal-embassy` on underlying `embassy-time-driver`'s tick-hz

### ISSUE THREAD

**Issue by doge-gif** [esp-rs/esp-hal#2985]
## Bug description

When using `esp-hal-embassy`, one cannot set `embassy-time`'s [tick rate](https://docs.rs/embassy-time/latest/embassy_time/#tick-rate).
This is due to esp-hal-embassy [hardcoding the value](https://github.com/esp-rs/esp-hal/blob/660e43effaa1ef6a0419db7c77a5034485ce9c41/esp-hal-embassy/Cargo.toml#L23), which embassy-time says not to do in libraries.

> When using embassy-time from libraries, you should not enable any tick-* feature, to allow the end user or the driver to pick.

## To Reproduce

1. Start a blank project
2. Add following to cargo.toml's dependency:

```toml
esp-hal-embassy = { version = "^0.6.0", features = ["esp32-c3"] }
# anything other than tick-hz-1_000_000
embassy-time = { version = "^0.4.0", features = ["tick-hz-2_000_000"] }
```

minimal repro: TBD

## Expected behavior

We should be able to (within a reasonable extent) change the underlying tick rate.

## Environment

- Target device: ESP32-C3, but really any device
- Crate name and version: esp-hal-embassy 0.6.0

## Notes

I haven't deciphered the hal codebase yet (I'm a newcomer to rust overall), so I don't know if this is due to a hardware limitation, or just simple oversight.
